apiVersion: apps/v1
kind: Deployment
metadata:
  name: idrak-db
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idrak-db
  template:
    metadata:
      labels:
        app: idrak-db
    spec:
      nodeSelector:
        node-role: worker2   # Pin DB to a worker node
      containers:
        - name: mongo
          image: bilal312/idrak-db:v1
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: diary-secret
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: diary-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
